// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVMQhdj9tAxAnCvAwRuuOeogod6HrBkfM',
    appId: '1:1025542183260:android:c839331cb2733ba6964999',
    messagingSenderId: '1025542183260',
    projectId: 'my-project-4120f',
    storageBucket: 'my-project-4120f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcE6K04YqQtGgW8G8a861bY6gbjyN_AFA',
    appId: '1:1025542183260:ios:7dcfcb26c0e70243964999',
    messagingSenderId: '1025542183260',
    projectId: 'my-project-4120f',
    storageBucket: 'my-project-4120f.appspot.com',
    androidClientId: '1025542183260-81cbo0hiuojttcs56sab6kr16go8vtf5.apps.googleusercontent.com',
    iosClientId: '1025542183260-i40v3jlk9nr9k0uf1675au9k8nlndlmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );
}
